---
version: "2.1"
services:
  heimdall:
    image: aleixmt/digitalization-dashboard:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 1080:80
    restart: unless-stopped
    volumes:
      - ./config:/config
