---
version: "2.1"
services:
  heimdall:
    image: aleixmt/digitalization-dashboard:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
    ports:
      - "0.0.0.0:80:80"
    restart: unless-stopped
    volumes:
      - ./config:/config
